server:
  port: 80
spring:
  application:
    name: cloud-consumer-openfeign-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
# OpenFeign性能优化 HttpClient5 暂未完成
    openfeign:
      client:
        config:
          default: # 全局配置
            connect-timeout: 3000 # 连接超时时间 3s
            read-timeout: 3000 # 读取超时时间
      compression: # 启用 HTTP 请求和响应压缩的配置 启用压缩可以减少网络带宽的使用，并提高传输效率
        request:
          enabled: true
          min-request-size: 2048
          mime-types: text/xml,application/xml,application/json
        response:
          enabled: true
logging:
  level:
    com:
      jlf:
        cloud:
          apis:
            PayFeignAPI: debug